<?php

namespace AppBundle\Repository;

/**
 * OfferBookmarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferBookmarkRepository extends \Doctrine\ORM\EntityRepository
{
}
